services:
  postgres_db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/postgresql/data
      - ./sqls:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres_db
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - postgres_db

  mynginx:
    image: nginx:1.13.6-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./sanic.conf:/etc/nginx/conf.d/app.conf
    restart: always

volumes:
  postgres_data:

networks:
  default:
    driver: bridge